database:
  host: 127.0.0.1
  port: 5432
  user: postgres
  password: postgres
  dbname: portfolio_management_db

streamlit_server:
  host: 0.0.0.0
  port: 8501

Model_config:
  model_name: "Name of model"
  max_tokens: 1024
  temperature: 0.7
  top_p: 1.0

